### ISSUE TITLE
Fix edit link for Collections

### ISSUE THREAD

**Issue by metasj** [Innovation-Information-Initiative/Open-Innovation-Dataset-Index#99]
When viewing a collection, the edit link takes you to the sheet (datasets worksheet); it should take you to the appropriate github page.

**Comment by metasj** [comment]
One remaining bug: the [NBER collection](https://iiindex.org/collections/nber) 
links to https://github.com/Innovation-Information-Initiative/Open-Innovation-Dataset-Index/blob/main/collections/nber.md
when it should be to the all-caps version, https://github.com/Innovation-Information-Initiative/Open-Innovation-Dataset-Index/blob/main/collections/NBER.md

**Comment by agnescameron** [comment]
this is sorted for now, but I'll add a script that enforces lower case on files -- the way the linking works is to get the window location from the page url, which appears to be always lower-case
